/*MANUAL

CASO NAO ESTEJA MUITO PACIENTE EXPERIMENTE PULAR PARA O RESUMO QUE
TEM A PARTIR DA LINHA 90, ABAIXO SEGUE-SE UMA DESCRICAO MAIS DETALHADA 
DOS COMANDOS ATE A LINHA 86.

FOR ENGLISH GUIDE GO TO LINE 122.

________________________________________________________
COMANDOS QUE ATUAM NO TERRENO/NAVEGACAO:
-POSICAO:
SETA ESQUERDA: MOVE O TERRENO PARA ESQUERDA
SETA DIREITA: MOVE O TERRENO PARA DIREITA
SETA PRA CIMA: MOVE O TERRENO PARA CIMA
SETA PRA BAIXO: MOVE O TERRENO PARA BAIXO

-ZOOM:
TECLA "Q": APROXIMA O TERRENO (ZOOM IN)
TECLA "W": AFASTA O TERRENO (ZOOM OUT)

-ROTACAO
TECLAS "A" e "S"
________________________________________________________
COMANDOS QUE ATUAM NO OBJETO:
recomendo a principio afastar o terreno usando a tecla "W" para ter uma
nocao melhor de espaco quando for criar seu primeiro objeto

-SELECIONAR OBJETO:
"M"=CASA
"N"=PALMEIRA
"B"=ALGA VERMELHA
"V"=AVIAO
"C"=CABANA
"X"=ANEMONA
"Z"=COGUMELO
"L"=PREDIO
"K"=ARVORE
"J"=MONTANHA
"H"=NUVEM
"G"=AGUA
"F"=FABRICA
"D"=CRISTAL
"P"=FLOR 1
"O"=FLOR 2
"I"= CAPIM
"U"= ASFALTO (RETA)
"Y"= ASFALTO ("CURVA")
"T"= CORAL
"R"= OUTDOOR
"E"= PEDRA
"0"= CERVO
"1"= PEIXE
"2"= PINHEIRO
"3"= ARBUSTO
"4"= CACHOEIRA
"5"= COLINA
"6"= AREIA
"7"= PROPRIEDADE RURAL
"8"= RETANGULO
"9"= ANTENA

caso vc tenha apertado algum destes botoes e nao tenha visto o objeto
experimente mover o mouse para situar-lo em seu campo de visao

(APERTE A TECLA DO RESPECTIVO OBJETO ANTES PARA PODER VISUALIZAR-LO)
-DEFINIR TAMANHO DO OBJETO:
PARA AUMENTAR A ALTURA DO OBJETO PRESSIONE "." 
PARA DIMINUIR A ALTURA DO OBJETO PRESSIONE ","
PARA AUMENTAR A LARGURA DO OBJETO PRESSIONE "/" 
PARA DIMINUIR A LARGURA DO OBJETO PRESSIONE  ";"


-POSICIONAR OBJETO:
VERTICAL: CONFORME A POSICAO VERTICAL DO MOUSE
HORIZONTAL 1: CONFORME A POSICAO HORIZONTAL DO MOUSE
HORIZONTAL 2: TECLAS "[" e "]"

-ROTACIONAR OBJETO:
TECLAS "-" E "="

-CRIAR OBJETO:
CLIQUE COM O BOTAO ESQUERDO DO MOUSE E O OBJETO SERA GRAVADO
DA FORMA COMO VOCE DETERMINOU 

-BACKSPACE: NENHUM OBJETO APARECE PARA SER CRIADO ATÉ QUE VOCE PRESSIONE 
ALGUMA DAS TECLAS DE SELACAO DE OBJETO
__________________________________________________________________________
____________________________________RESUMO________________________________
__________________________________________________________________________
CASO TENHA FICADO CONFUSO EIS UM RESUMO PRA VOCE PODER IR TESTANDO E INTUINDO
POR CONTA PROPRIA:

TERRENO

-COORDENADAS DO TERRENO:
TECLAS: SETA DIREITA, SETA ESQUERDA, CIMA, BAIXO, "Q", "W", "A", "S"

SUGIRO POSICIONAR O TERRENO NO MEIO DA TELA DE UMA FORMA QUE
TODA A SUA EXTENSAO ESTEJA VISIVEL
_________________________________________
OBJETO:

VISUALIZAR OBJETO: M,N,B,V,C,X,Z,L,K,J,H,G,F,D,P,O,I,U,Y,T,R,E,0,9,8,7,6,5,4,3,2,1
(CADA TECLA CORRESPONDE A UM OBJETO DIFERENTE)
-TAMANHO DO OBJETO
"." AUMENTA A ALTURA DO OBJETO E "," PARA DIMUIR
"/" AUMENTA A LARGURA DO OBJETO E ";" PARA DIMINUIR

-POSICAO DO OBJETO
POSICAO HORIZONTAL(X) E VERTICAL(Y): POSICAO DO MOUSE
POSICAO HORIZONTAL(Z): TECLAS "[" e "]"

-RODAR OBJETO:
TECLAS "-" e "='

BOTAO ESQUERDO DO MOUSE (CRIA O OBJETO)

BACKSPACE: NENHUM OBJETO SELECIONADO 

___________________________________________________________________
-----------------------------ENGLISH-------------------------------
LAND

-LAND COORDINATES:
KEYS: RIGHT, LEFT, UP, DOWN, "Q", "W", "A", "S"

_________________________________________
OBJECT:

SELECT OBJECT: M,N,B,V,C,X,Z,L,K,J,H,G,F,D,P,O,I,U,Y,T,R,E,0,9,8,7,6,5,4,3,2,1
(EACH KEY IS A DIFFERENT OBJECT)
-OBJECT SIZE
"." INCREASES THE HEIGHT 
"," DECREASES THE HEIGHT
"/" INCREASES THE WIDTH
";" DECREASES THE WIDTH

-OBJECT POSITION
HORIZONTAL(X) AND VERTICAL(Y): MOUSE POSITION 
HORIZONTAL(Z): KEYS "[" AND "]"

-ROTATE OBJECT:
KEYS "-" AND "='

LEFT CLICK: CREATES THE OBJECT

BACKSPACE: NO OBJECT SELECTED

*/
