//MANUAL

//CASO NAO ESTEJA MUITO PACIENTE EXPERIMENTE PULAR PARA O RESUMO QUE
//TEM A PARTIR DA LINHA 95, ABAIXO SEGUE-SE UMA DESCRICAO MAIS DETALHADA 
//DOS COMANDOS ATE A LINHA 92.

//________________________________________________________
//COMANDOS QUE ATUAM NO TERRENO/NAVEGACAO:
//-POSICAO:
//SETA ESQUERDA: MOVE O TERRENO PARA ESQUERDA
//SETA DIREITA: MOVE O TERRENO PARA DIREITA
//SETA PRA CIMA: MOVE O TERRENO PARA CIMA
//SETA PRA BAIXO: MOVE O TERRENO PARA BAIXO

//-ZOOM:
//TECLA "Q": APROXIMA O TERRENO (ZOOM IN)
//TECLA "W": AFASTA O TERRENO (ZOOM OUT)

//-ROTACAO
//TECLA"A": ROTACIONA O TERRENO PARA ESQUERDA
//TECLA"S": ROTACIONA O TERRENO PARA DIREITA
//________________________________________________________
//COMANDOS QUE ATUAM NO OBJETO:
//recomendo a principio afastar o terreno usando a tecla "W" para ter uma
//nocao melhor de espaco quando for criar seu primeiro objeto

//-SELECIONAR OBJETO:
//"M"=CASA
//"N"=PALMEIRA
//"B"=ALGA VERMELHA
//"V"=AVIAO
//"C"=CABANA
//"X"=ANEMONA
//"Z"=COGUMELO
//"L"=PREDIO
//"K"=ARVORE
//"J"=MONTANHA
//"H"=NUVEM
//"G"=AGUA
//"F"=FABRICA
//"D"=CRISTAL
//"P"=FLOR 1
//"O"=FLOR 2
//"I"= CAPIM
//"U"= ASFALTO (RETA)
//"Y"= ASFALTO ("CURVA")
//"T"= CORAL
//"R"= OUTDOOR
//"E"= PEDRA
//"0"= CERVO
//"1"= PEIXE
//"2"= PINHEIRO
//"3"= ARBUSTO
//"4"= CACHOEIRA
//"5"= COLINA
//"6"= AREIA
//"7"= PROPRIEDADE RURAL
//"8"= RETANGULO
//"9"= ANTENA

//caso vc tenha apertado algum destes botoes e nao tenha visto o objeto
//experimente mover o mouse para situar-lo em seu campo de visao

//-DEFINIR TAMANHO DO OBJETO:
//PRESSIONE A RESPECTIVA TECLA DO OBJETO QUE VOCE QUER CRIAR(CHAMAREI DE "ESSA TECLA")
//PARA AUMENTAR A ALTURA DO OBJETO PRESSIONE "ESSA TECLA" JUNTO COM A TECLA "." 
//PARA DIMINUIR A ALTURA DO OBJETO PRESSIONE "ESSA TECLA" JUNTO COM A TECLA ","
//PARA AUMENTAR A LARGURA DO OBJETO PRESSIONE "ESSA TECLA" JUNTO COM A TECLA "/" 
//PARA DIMINUIR A LARGURA DO OBJETO PRESSIONE "ESSA TECLA" JUNTO COM A TECLA ";"
//EX: PRESSIONE "9"+"." E APOS ALGUNS SEGUNDOS VERA QUE A "ANTENA" PARECE
//CRESCER EM ALTURA

//-POSICIONAR OBJETO:
//VERTICAL: CONFORME A POSICAO VERTICAL DO MOUSE
//HORIZONTAL 1: CONFORME A POSICAO HORIZONTAL DO MOUSE
//HORIZONTAL 2: CLIQUE COM O BOTAO DIREITO DO MOUSE:
//SE O MOUSE ESTIVER A ESQUERDA DA TELA O OBJETO SE MOVERA PARA A ESQUERDA
//ENQUANTO O BOTAO ESTIVER PRESSIONADO
//SE O MOUSE ESTIVER A DIREITA DA TELA O OBJETO SE MOVERA PARA A DIREITA
//ENQUANTO O BOTAO ESTIVER PRESSIONADO
//obs: horizontal 1 e horizontal 2 tendem a se confundir caso o terreno
//seja rotacionado, nada tao grave que nao possa ser intuido com tranquilidade.

//-ROTACIONAR OBJETO:
//PRESSIONE A TECLA QUE DEFINE O OBJETO JUNTO COM A TECLA "="(provavelmente 
//ela vai junto da tecla "+" no seu teclado)
//EX: PRESSIONE "J" E "=" JUNTO E A "MONTANHA" VAI RODAR ENQUANTO ESSAS
//TECLAS ESTIVEREM PRESSIONADAS JUNTAS

//-CRIAR OBJETO:
//CLIQUE COM O BOTAO ESQUERDO DO MOUSE E O OBJETO SERA GRAVADO
//DA FORMA COMO VOCE DETERMINOU 

//__________________________________________________________________________
//____________________________________RESUMO________________________________
//__________________________________________________________________________
//CASO TENHA FICADO CONFUSO EIS UM RESUMO PRA VOCE PODER IR TESTANDO E INTUINDO
//POR CONTA PROPRIA:

//TERRENO

//-COORDENADAS DO TERRENO:
//TECLAS: SETA DIREITA, SETA ESQUERDA, CIMA, BAIXO, "Q", "W", "A", "S"
//SUGIRO POSICIONAR O TERRENO NO MEIO DA TELA DE UMA FORMA QUE
//TODA A SUA EXTENSAO ESTEJA VISIVEL
//_________________________________________

//OBJETO:

//-TAMANHO DO OBJETO
//J+"." AUMENTA A ALTURA DO OBJETO E J+"," PARA DIMUIR
//J+"/" AUMENTA A LARGURA DO OBJETO E J+";" PARA DIMINUIR
//PODE SER "J" OU:L,K,H,G,F,D,M,N,B...(QUALQUER TECLA DA LISTA DE OBJETOS)

//-RECURSOS DO MOUSE UTILIZADOS:
//BOTAO DIREITO DO MOUSE (POSICAO DO OBJETO)
//BOTAO ESQUERDO DO MOUSE (CRIA O OBJETO)
//POSICAO HORIZONTAL E VERTICAL DO MOUSE (POSICAO DO OBJETO)

//-RODAR OBJETO:
//J+"="
//NOVAMENTE, PODE SER "J" OU QUALQUER UMA DAS LETRAS QUE ESTA NA LISTA DE
//SELECIONAR OBJETOS
